### PR TITLE
ctf_chat: Implement colored PMs

### PR DESCRIPTION
**Pull request by ClobberXD**
This PR re-implements coloured PMs, this time in `ctf_chat`.

### CODE REVIEW

**Comment by xenonca** [comment]
Tried it, works well but the color is a bit too light imo, making it darker would be cool to distinguish it better from blue team messages:
scs

**Comment by ClobberXD** [comment]
Thanks for testing! Let me know if this is better:

screenshot_20190708_164226

**Comment by Thomas--S** [comment]
I didn't test this in-game, but I guess that this color might be a little bit difficult to read during night time.

I'd suggest to use a more "alerting" color because private messages are usually rather important and should not be missed.

How about a color similiar to the orange from the afk kick warnings?

**Comment by ClobberXD** [comment]
The orange/yellow hue is generally used for server messages like the aforementioned afkkick warnings, respawn immunity message, medkit healing interruption message, and the like. I thought it's better to keep those colours separate from chat-related stuff.

Also:
screenshot_20190709_110055

**Comment by LoneWolfHT** [comment]
How does `#00ff00` look as a PM color?

**Comment by ClobberXD** [comment]
This is very similar to the colour used to display IRC channel messages in-game.

**Comment by LoneWolfHT** [comment]
> This is very similar to the colour used to display IRC channel messages in-game.

How about `#e043ff` then?

**Comment by ClobberXD** [comment]
screenshot_20190710_092555
screenshot_20190710_092713

**Comment by LoneWolfHT** [comment]
That looks good

**Comment by LoneWolfHT** [comment]
Tested. Works :+1:

**Comment by xenonca** [comment]
Since it's not yet merged anyway, what about changing ``PM`` to ``DM``?

**Comment by Thomas--S** [comment]
Actually, I'd prefer `PM`, it seems to be more popular, imho.

**Comment by LoneWolfHT** [comment]
DM is used for 'Dungeon Master' in Minetest

**Comment by xenonca** [comment]
True, ok, we don't want anyone to send Dungeon Masters around :P

**Comment by ClobberXD** [comment]
DMs don't exist outside of Discord, at least when it comes to MT, even on IRC (although it's technically called a query). So I'd prefer to stick to PM as well.

**Pull request closed without merging**
